spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gavroche
    username: gavroche
    password:

  jpa:
    properties:
      hibernate:
        default_schema: public

  liquibase:
    enabled: true
    change-log: db/changelog/master.yml